# Generated by Django 5.1.1 on 2024-10-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_category_alter_listing_image_url'),
    ]

    operations = [
    ]
